[정렬]9월 3일
Altu-Bitu/Altu-Bitu-HJ pull request #1
Opened 2021-09-04 15:27 UTC by rajoo1120

과제제출합니다~~

2021-09-05 04:16 UTC, HyunJiLim0406 reviewed
p3
진짜 잘 작성하셨어요! 주석도 꼼꼼하게 달아주셔서 이해하기도 쉬웠구요!
제가 코드에 남긴 코멘트만 참고해주세요. 이대로 Merge 해도 될 것 같습니다!

만약 아직 안푸신 문제들을 더 풀게 된다면, 다 풀고 리뷰어에 저 클릭해서 호출해주세요!
수고하셨습니다 🖐

2021-09-05 04:16 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1026.cpp
> +    sort(B.begin(),B.end());
👍

2021-09-05 04:16 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1026.cpp
> +    //최소값을 만듦
하나를 내림차순으로 정렬하는 것도 좋아요~

2021-09-05 04:16 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/10994.cpp
> +    //이때 작은 박스는 위옆 모두 idx+2지점에서 시작
주석 좋아요!

2021-09-05 04:16 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/10994.cpp
> +            arr[i][j] = ' ';
2차원 벡터를 사용하면 한 줄로 assign 할 수 있는 방법이 있어요! 한 번 알아보시겠어요?

2021-09-05 04:16 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/11651.cpp
> +        return a.second < b.second;
if 문에 걸렸다면 true/false 둘 중 하나는 무조건 리턴했을테니 else는 지워도 괜찮아요!

2021-09-05 04:16 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1316.cpp
> +        }
이 코드도 너무 좋지만 이 부분을 함수화 한다면 flag 변수를 쓰지 않아도 돼요!
그리고 `alp[(int)str[j]-97]>1` 부분을 보면 해당 값이 1보다 크기만 하면 해당 조건이 true를 반환하게 되는데요.
그럼 int 형 배열말고 다른 방법도 있지 않을까요?

아스키코드 잘 활용하셨어요! 근데 숫자 실수를 할 수도 있으니 `str[j]-'a'` 이런식으로 해도 좋아요!

2021-09-05 04:16 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/13458.cpp
> +    long long sum=0; //최대 범위를 고려하여 데이터타입 큰거로
👍

2021-09-05 04:16 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/13458.cpp
> +                sum += (arr[i]/c)+1;
여기서 `(arr[i]/c)`가 중복되네요! 좋은 방법 없을까요?

2021-09-06 14:49 UTC, rajoo1120 commented
@HyunJiLim0406 
3문제 더 풀었습니다..! 그리고 기존에 풀었던 것들은 일단 그대로 올렸는데요,
_**그리고 alp[(int)str[j]-97]>1 부분을 보면 해당 값이 1보다 크기만 하면 조건이 true를 반환하게 되는데요.
그럼 int 형 배열말고 다른 방법도 있지 않을까요?**_ << 이부분에서 다른 방법이 뭘까요..? flag를 사용하는건가요?

2021-09-07 04:02 UTC, HyunJiLim0406 requested changes
p1
제가 알림을 못봐서 리뷰가 늦어졌네요..! 리뷰 요청 후 슬랙으로도 멘션해주시면 놓치지 않고 바로 확인하러 올게요!!
새롭게 푸신 문제들도 잘 푸셨는데 반드시 고쳐야할 부분이 한군데 보이네요! 꼭 수정해주세요

그리고 질문에 대한 답변 드릴게요
배열을 사용하는건 맞아요! 제가 드린 코멘트의 의미는 그 배열의 자료형이 꼭 int일 필요는 없다는 뜻이었어요!
알파벳은 이전에 등장했거나/안했거나 딱 두 가지 상태만 알면 될 것 같은데요. 두 가지 상태만 저장하는 자료형은 뭐였나요?

2021-09-07 05:26 UTC, HyunJiLim0406 reviewed
p3
잘 수정됐네요! 이제 merge 하셔도 됩니다!!

2021-09-07 05:26 UTC, HyunJiLim0406 commented on 9월 3일 - 정렬/1946.cpp
> +    {
👍

2021-09-07 07:10 UTC, merged