[분할 정복] 10월 10일
Altu-Bitu/Altu-Bitu-HJ pull request #10
Opened 2021-10-10 10:09 UTC by rajoo1120

필수문제 2문제 포함 총 3문제 제출합니다! 
시험기간이라 풀 시간이 너무 부족해서 나머지 2문제는 추가제출로 올라오는 샘플코드에 주석달아서 올리겠습니다ㅜ.ㅜ 

17281번은 푼다고 풀었는데 돌아가지 않아서.. 어떻게 고쳐야할지 힌트를 주신다면 감사합니다..

2021-10-10 10:33 UTC, bsa0322 requested changes
p1. 17281 수정 후, 저 다시 리뷰어로 호출해주세요!!! 수고하셨습니다~!

2021-10-10 10:33 UTC, bsa0322 commented on 10월 5일 - 분할 정복/1244.cpp
> +                is_switched[num-i] =!is_switched[num-i];
p3. for문 내에 조건문이 다소 복잡하네요! for문 내의 조건은 단순화시키고, 현재 조건처리는 반복문 안에서 if문으로 하시면 가독성도 올라가고 더 좋을 것 같아요!

2021-10-10 10:33 UTC, bsa0322 commented on 10월 5일 - 분할 정복/17281.cpp
> +    }
p1. 입력의 인덱스 증가 변수에 문제가 있네요! 이 부분 수정하면 바로 맞으시지 않을까 싶습니다!

2021-10-10 10:33 UTC, bsa0322 commented on 10월 5일 - 분할 정복/1802.cpp
> +        }
p3. 주어지는 입력은 항상 2^n-1꼴이라 하네요! 이 부분은 그럼 꼭 필요할까요?

2021-10-11 12:37 UTC, bsa0322 requested changes
p1. 17281 틀렸습니다 나오네요! 관련 코멘트 추가했어요. 수정 후 다시 리뷰어 호출해주세요~!!

2021-10-11 12:37 UTC, bsa0322 commented on 10월 5일 - 분할 정복/17281.cpp
> +        else is_ground[n-1]=true; //아니면 필드 진출
p1. 특정 필드(루, 베이스)에 선수가 없는데 홈런일 시 점수를 계속 증가시키면 어떻게 되나요? 지금 해당 코드의 위치가 잘못되었어요!

2021-10-12 01:12 UTC, rajoo1120 commented
야구문제 최종 수정해서 올리고, 못풀었던 선택2문제 주석달아서 추가로 올렸습니다!
확인부탁드립니다:)

2021-10-15 07:18 UTC, merged