[최단경로] 11월 7일
Altu-Bitu/Altu-Bitu-HJ pull request #13
Opened 2021-11-07 14:25 UTC by rajoo1120

세문제 제출합니다! 나머지 두문제는 풀 수 있으면 풀어서 제출하고 안되면 추가제출하겠습니다.

+)1063번은 예시6개를 그냥 넣어서 돌렸을땐 다 맞게 나오는데, 백준에 제출하면 틀렸다고 뜨네요..

2021-11-08 05:18 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다! 코멘트 달았으니 확인해주세요
다른 사람의 코드를 보며 공부할 땐 가능하면 많은 코드를 읽어보세요!
그리고 그 사람들이 왜 그렇게 코드를 작성했는지 고민해보면 어떤게 좋은 코드고 어떤게 나쁜 코드인지 알 수 있어요

제 생각에 15685번은 레퍼런스가 있을 것 같네요! 표기해주시고 코멘트 참고해서 꼭 수정해주세요
수정하시고 리뷰어로 저 불러주세요~

2021-11-08 05:18 UTC, HyunJiLim0406 commented on 11월 2일 - 최단경로/1063.cpp
> +//함수가 엄청 복잡하게 됐는데 어떻게 해야 간단하게 만들 수 있을지 모르겠네요..
한참 들여다 봤는데 오타가 문제였네요 🤣
한 번 찾아보세요!

2021-11-08 05:18 UTC, HyunJiLim0406 commented on 11월 2일 - 최단경로/1063.cpp
> +        if(input==di[i]){
매번 for문을 최대 8번씩 도는건 효율적이지 않아요!
바로 움직일 방향을 찾을 수 있는 방법은 없을까요?

2021-11-08 05:18 UTC, HyunJiLim0406 commented on 11월 2일 - 최단경로/1063.cpp
> +    cout << (char)(kx+'A'-1)<<ky<<"\n"<<(char)(sx+'A'-1) <<sy;
이건 출력만 하면 되는거라 이렇게해도 괜찮지만, string 형식으로 리턴하는 연습을 하셔도 좋습니다!

2021-11-09 08:44 UTC, rajoo1120 commented
코멘트 주신 것들 다 수정했는데, 
드래곤커브 문제에서,, 코멘트 주신대로 범위 검사 굳이 할 필요 없다는거 알고 뺐고, temp대신 size만 따로 저장하는 변수를 만들어서 썼는데 오류가 나네요. ㅜ.ㅜ 계속 봤는데 제가 놓치고 있는 부분이 있는건지 잘 모르겠습니다. 혹시 힌트를 주실 수 있을까요?

2021-11-09 10:34 UTC, HyunJiLim0406 reviewed
p3
수고하셨습니다! 잘 수정하셨네요~
드래곤 커브 문제 틀린 이유는 코멘트로 달아놓았으니 확인해주세요!
사소한 수정사항이라 그거 수정되면 바로 머지하셔도 됩니다!

2021-11-16 08:03 UTC, merged