[스택, 큐, 덱] 9월 14일
Altu-Bitu/Altu-Bitu-HJ pull request #3
Opened 2021-09-14 06:52 UTC by rajoo1120

20920번에 계속 시간초과가 뜨고,
1935번에서 다른 입력은 잘 나오는데, 마지막에 빈배열이면 에러를 출력하는게 안됩니다.
코드 리뷰 부탁드립니다.. ㅜ.ㅜ

2021-09-14 07:05 UTC, rajoo1120 commented
뭐가 꼬였는지 번호가 뒤죽박죽이 돼서 다시 올렸습니다
20920번에 계속 시간초과가 뜨고,
**1935번이 아니라 5430번에서** 다른 입력은 잘 나오는데, 마지막에 빈배열이면 에러를 출력하는게 안됩니다.

2021-09-15 04:13 UTC, HyunJiLim0406 requested changes
p2(20920 제외)
수고하셨습니다! 논리나 시간복잡도 면에서 개선할 부분은 크게 없어요! 다만 p2인 이유는 리팩토링을 통해 메인이 짧아지고, 인덴테이션 depth도 줄일 수 있는 부분이 있기 때문입니다.
20920번 시간초과 이유는 코드에 적어뒀어요~ 

어..그리고 5430번은 문제가 없어보입니다! 마지막에 빈배열이면 에러를 출력하는게 어떤 뜻일까요?
마지막에 빈배열만 남았더라도 에러가 아닌 경우도 있어요~ 한 번 잘 생각해보세요!

20920번 수정하고 다른 코드들도 리팩토링한 뒤 다시 리뷰어로 저 호출해주세요!

2021-09-15 04:13 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/20920.cpp
> +bool cmp(string a, string b) {
인자를 다시 한 번 볼까요!
슬랙의 '수업-질문' 채널에서 가장 최근 메세지가 도움이 될거예요!

2021-09-15 04:13 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/20920.cpp
> +    for (int i=0; i<n; i++){
여기 i는 쓰지 않는 것 같네요! while로 바꾸면 변수를 아낄 수 있겠죠!!

2021-09-15 04:13 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/5430.cpp
> +        }
여기를 dq를 리턴하는 함수로 뺄 수 있어보여요!

2021-09-15 04:13 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/5430.cpp
> +        bool isError= false; //에러인지 검사
👍
앗 근데 이건 변수니까 스네이크 표기법 사용하셔야해요!

2021-09-15 04:13 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/5430.cpp
> +                isReversed = !isReversed;
하핳 맞아요

2021-09-15 04:13 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/5430.cpp
> +        if (!isError) {
여기 인덴테이션이 너무 깊게 들어가네요...! 리팩토링 고민해보세요!

2021-09-15 04:13 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/kakao.cpp
> +            {
인형을 열마다 스택에 담는 전처리를 한다면 코드가 좀 더 깔끔해질거예요!

2021-09-15 06:04 UTC, rajoo1120 commented
코멘트 주신부분들 전부 수정해서 업데이트 했습니다! 
근데
_이 방법도 좋은데요! 연산자들의 우선순위를 리턴하는 함수를 만들거나 연산자들의 우선순위를 map 등으로 저장하면 이 부분 코드를 하나로 합칠 수 있지 않을까요?_ 
이부분을 수정해봤는데 코드가 돌아가지 않습니다.. ㅠㅠ '('에도 우선순위를 적용해야 하는 걸까요?

2021-09-15 07:21 UTC, HyunJiLim0406 reviewed
p3
잘 수정하셨어요! 1918번이 돌아가지 않은 이유는 예상하신대로 괄호 우선순위를 설정하지 않으셨기 때문이에요! '('의 우선순위가 default 값인 0이 됐기 때문에 우선순위가 가장 높아진거예요!

merge해도 괜찮은 코드지만 if문이 중첩해서 들어가는 부분이 몇군데 보여요! if문이 계속 중첩돼서 들어가면 보기에도 불편하고, 디버깅도 어려워지니 코드가 완성된 후 리팩토링하는 과정은 항상 필요해요!!

음 그러면 마지막으로 1918번만 한번 더 수정하고 머지하면 될 것 같습니다!
수정 후 저 호출하셔도 괜찮고 아니면 호출없이 바로 머지하셔도 크게 상관은 없어요!

2021-09-15 07:21 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/1918.cpp
> +    mp['-']=2;
이렇게 되면 괄호들의 우선순위가 0으로 셋팅되고, 가장 높은 우선순위가 돼요!
그래서 말씀하신대로 괄호의 우선순위도 설정하거나, 숫자가 클수록 우선순위를 높게 하는걸로 수정하셔야 합니다!

2021-09-15 07:21 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/1935.cpp
> +}
잘 수정하셨어요! 근데 그냥 계산 후 break없이 바로 리턴하면 result 변수도 필요없어요~

2021-09-15 07:21 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/20920.cpp
> +bool cmp(const string &a, const string &b) {
👍

2021-09-15 07:21 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/5430.cpp
> +}
👍

2021-09-15 07:21 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/kakao.cpp
> +        }
여기 if문이 중첩돼서 들어가네요! 어떻게 하면 끊어갈 수 있을까요?

2021-09-15 07:21 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/kakao.cpp
> +    }
잘하셨어요! 이걸 스택리턴 함수로 만들어도 좋아요~

2021-09-15 07:52 UTC, merged