Hw0918
Altu-Bitu/Altu-Bitu-HJ pull request #4
Opened 2021-09-18 10:27 UTC by rajoo1120

과제제출합니다!!!

2021-09-18 11:44 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다! 5문제 다 잘 푸셨어요~ 근데 왜 p1이냐면 음...큰 문제는 아니지만 주석의 내용을 커버리지 못하는 코드가 있기 때문입니다!
그리고 지금 대부분의 코드가 메인에 있는데, 함수화 할 수 있는건 없는지 다시 한 번 살펴볼까요?
조건문들도 리팩토링을 통해 짧고 간결하게 할 수 있는 부분이 보여요!

그리고 11286번은 지금도 좋지만 사실 우선순위 큐에서의 compare 함수를 정의해보셨으면 해서 낸 과제였습니다!
compare 함수 정의해서 쓰는걸로 수정해볼까요?

코드에 코멘트 확인해주시고, 수정 후 다시 리뷰어로 저 호출해주세요!

2021-09-18 11:44 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/11286.cpp
> +    priority_queue<pair<int, int>, vector<pair<int, int> >, greater<pair<int, int> > > pq;
이것도 좋지만 직접 cmp 함수를 정의해보시는건 어떨까요!

2021-09-18 11:44 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/11723.cpp
> +                cout << 0 << "\n";
이거는 한줄로 쓸 수도 있어요! 어떻게 할까요?

2021-09-18 11:44 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/11723.cpp
> +                visited[n]=true;
여기도 한 줄로 처리할 수 있어요~!

2021-09-18 11:44 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/11723.cpp
> +int main(){
잘 푸셨어요! 근데 어떤 방법을 사용하면, 이거랑 논리는 똑같은데 배열 없이 int 변수 하나로 문제를 풀 수 있어요!
비트마스킹에 대해 알아보세요! 좀 어려울수도 있어서 알아보기만 하셔도 좋아요!

2021-09-18 11:44 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/12018.cpp
> +        my.push_back(list[l-1]);
👍

2021-09-18 11:44 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/12018.cpp
> +    }
여기를 아예 while문 하나로 처리할 수도 있겠네요!

2021-09-18 11:44 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/15903.cpp
> +priority_queue<long long, vector<long long>, greater<long long>> pq;
맞아요~

2021-09-18 11:44 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/15903.cpp
> +    for(int i=0; i<n; i++){
여기서 i 변수는 사용하지 않네요..!

2021-09-18 11:44 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/3613.cpp
> +}
카멜표기법은 소문자로 시작합니다!
그리고 기왕 함수화한 김에 string을 리턴하도록 해서 convert된 결과를 리턴하게 하는건 어떨까요?
tolower, toupper 함수에 대해서도 알아보세요!

2021-09-18 11:44 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/3613.cpp
> +        err= true;
p1
이 조건문이 정말 에러1을 완전히 커버리지할까요?

2021-09-18 11:44 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/3613.cpp
> +        ConvertJava();
이것조 좋지만..! convert 함수처럼 c인지 java인지 판단하는 함수가 있다면 더 좋지 않을까요?

2021-09-19 07:02 UTC, rajoo1120 commented
코멘트 주신 부분 고쳐보고, 비트마스킹 버전도 만들어서 올려봤습니다.
근데 코멘트 주신 것 중에 
_여기를 아예 while문 하나로 처리할 수도 있겠네요!_ 
이부분은 my[i]에서 i를 사용해서 더해줘야해서 그냥 뒀는데 이걸 사용하지 않고 while문으로 바꾸는 방법을 모르겠네요 ... ㅜ.ㅜ

2021-09-19 08:06 UTC, HyunJiLim0406 reviewed
p3
수고하셨습니다! 아주 잘 수정하셨어요~ 비트마스킹 풀이까지 해주셨네요!
질문에 대한 답변은 코드에 달아놓았습니다!
아주 사소하게 수정할 수 있는 부분도 코드에 적어놓았는데요.
수정 후 바로 머지하셔도 되고 아니면 머지전에 다시 한 번 저한테 리뷰 요청하셔도 됩니다~! 👍

2021-09-19 08:06 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/3613.cpp
> +        err= true;
👍

2021-09-19 08:06 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/3613.cpp
> +}
이 부분은 리턴문 한 줄로 표현할 수 있네요!

2021-09-19 09:11 UTC, merged