[정수론] 9월 22일
Altu-Bitu/Altu-Bitu-HJ pull request #5
Opened 2021-09-22 12:25 UTC by rajoo1120

과제 제출합니다!
20302번을 돌리면 ourofbound 런타임에러가 뜹니다.. 
그리고 외계인의 기타연주가 if문이 너무 많아서 깔끔하지 않네요 ㅜ.ㅜ

2021-09-22 14:48 UTC, HyunJiLim0406 requested changes
p2(20302 제외)
수고하셨습니다! 20302번 틀린이유는 코드에 적어뒀어요!
그리고 2841번은 조금만 리팩토링 해볼까요?
(와우 깜짝이야 리뷰한거 날라간 줄 알았네요)
아무튼 그 외에도 코드에 남긴 코멘트 한 번씩 고민해주세요~
수정 후 저 리뷰어로 호출해주세요! 조금만 더 하면 되겠네요!!! 😉

2021-09-22 14:48 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/11050.cpp
> +        return factorial(num-1)*num;
if문에 걸리면 반드시 true/false를 리턴해요! 그럼 line12가 필요할까요?

2021-09-22 14:48 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/20302.cpp
> +    for(int i = 2; i <= MAX; i++) prime[i] = i;
*prime 배열을 MAX 크기로 할당했는데 `prime[MAX]`를 참조하는 경우가 있네요! 핳 저희가 한 실수랑 같은거네요 🙄
그리고 실수가 하나 더 있는데요..! 이건 직접 찾으시는게 좋을 것 같아요! 힌트를 드리자면...clion을 사용한다면 바로 눈치챌 수 있는 실수예요! 하나 더 드리자면...발견하시고 약간 헛웃음이 날 수도 있어요

2021-09-22 14:48 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/20302.cpp
> +// 36이면 3*3*2*2 로 나눠서 primeCnt[2]가 2 primeCnt[3]이 2가 됨
맞아요!

2021-09-22 14:48 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/20302.cpp
> +void eraseNum(int num){
이 함수랑 separateNum 함수를 합칠 수도 있어요! 근데 이렇게 분리해도 괜찮아요~

2021-09-22 14:48 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/20302.cpp
> +    bool banMinCho = false; //치약인지 민초인지
변수명이 재밌네요 🤣
근데 저희 변수명은 스네이크 표기법입니다!

2021-09-22 14:48 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/20302.cpp
> +
여기도 스네이크 표기법으로 바꿔주세요!

2021-09-22 14:48 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/2436.cpp
> +//즉, L/G의 약수 중에 서로소인 것을 찾으면 됨
완벽하네요

2021-09-22 14:48 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/2436.cpp
> +    }
범위 잘 짚으셨네요!
근데 지금 로직을 보면 x를 계속 갱신하다가 마지막에 구해진 x를 사용하네요!
그렇다면 가장 처음 구해진 x가 답이라고 판단할 수 있는 방법도 있겠네요~!

2021-09-22 14:48 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/2841.cpp
> +        }
여기서 continue로 끊어가도 좋겠네요!

2021-09-22 14:48 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/2841.cpp
> +    while(n--){
p2
핳 이정도면 아주 복잡하진 않은데요..! 주석을 자세하기 적어주셔서 읽는데 어려움은 없었어요!
근데 리팩토링할 수 있는 방법이 있겠죠?
딱 2가지 경우만 생각할까요? push를 하는 경우와 pop을 하는 경우로요! pop을 하는 연산 딱 하나와 push를 하는 연산 딱 하나만 있으면 돼요!
지금 코드에서 pop/push를 하는 조건을 다 정리해보세요! 하나로 합칠 수 있어요

2021-09-22 14:48 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/6588.cpp
> +    ios_base::sync_with_stdio(false); cout.tie(NULL); cin.tie(NULL);
이건 메인에 있는게 좋아요!

2021-09-22 14:48 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/6588.cpp
> +            prime.push_back(i);
아하 홀수 소수들을 전부 배열에 넣는거네요! 이것도 좋은 방법이에요~
근데 이 문제는 소수의 경로를 알 필요가 없어서 그냥 prime 또는 visited를 bool로 처리해도 돼요
그리고 이후 로직이 다 메인에서만 이루어지니 이 함수가 prime 벡터를 반환해도 좋겠네요!

2021-09-22 14:48 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/6588.cpp
> +            {
핳 여기서 결국 visited와 prime을 둘 다 쓰게 되네요
두 벡터를 bool 자료형으로 바꾸면 어떻게 될까요?

2021-09-22 16:22 UTC, rajoo1120 commented
바보같은 실수때문에 .. 민망하지만.. 리뷰 부탁드립니다!!!!! 👩🤛🤛🤛😭

2021-09-23 02:38 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다! 잘 수정해주셨는데 2436번이 안돌아가네요! 코멘트 봐주세요~
2841번은 더 리팩토링하면 좋겠지만, 어려우시다면 그냥 샘플코드 업로드 됐을 때 확인만 해주세요! 지금 코드도 아주 복잡한 코드는 아니니까요!!

수정 후 리뷰어로 저 호출해주세요!

2021-09-23 02:38 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/2436.cpp
> +    }
p1
이거 안돌아가네요! 확인해주세요~
지금 이코드면 두 자연수의 합이 최대가 되는 숫자들이 나올거예요!

2021-09-23 02:38 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/2841_new.cpp
> +        if(s[play.first].empty())
한 번만 더 생각해볼까요? 지금 코드는 스택의 empty 여부를 기준으로 조건문이 나뉘는데요
push랑 pop연산에 집중해봅시다!! empty는 기준이 아니라 조건의 일부일 뿐이에요!

2021-09-23 02:38 UTC, HyunJiLim0406 commented on 9월 17일 - 정수론/6588.cpp
> +            {
좋아요~!

2021-09-23 04:55 UTC, rajoo1120 commented
2436번, 6588번 둘 다 처음에 코멘트 주신 것처럼 고쳐보고싶었는데 잘 모르겠네요..
샘플코드 올라오면 확인하겠습니다!(둘다 이제 잘 돌아갑니다)

2021-09-23 04:58 UTC, HyunJiLim0406 reviewed
p3
좋아요! 그럼 이제 머지하셔도 됩니다~
6문제 다 푸셨으니 쿠폰 기록하겠습니다!

2021-09-23 07:49 UTC, merged