[브루트 포스] 9월 25일
Altu-Bitu/Altu-Bitu-HJ pull request #6
Opened 2021-09-25 11:21 UTC by rajoo1120

과제제출합니다.. 🦔

2021-09-25 12:40 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다! 20055번 덱 풀이는 생각도 못했던 거라 재미있었어요~
근데 돌아가지 않는 문제가 있네요! 확인해주세요~
그리고 2503번과 2858번은 좀 더 리팩토링할 수 있어요! 거기도 수정해봐요!
수정 후 리뷰어로 저 호출해주세요~

2021-09-25 12:40 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/20055.cpp
> +        deployment();
역할이 명확하게 구분돼서 좋네요!

2021-09-25 12:40 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/20055.cpp
> +void rotation(){
저희가 원래 이 문제에서 회전을 직접 구현하는걸 지양하려고 하는데
오호...덱은 생각 못했네요. 이것도 회전을 직접 구현한 셈이지만 효율적인 풀이라고 생각합니다! 👍
그래도 덱도 없고, 회전을 직접 구현할 수도 없다면 어떻게 구현해야할지도 고민해보세요!

2021-09-25 12:40 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2108.cpp
> +                break;
원래 입력이 음수였다면 어떻게 되나요?

2021-09-25 12:40 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2108.cpp
> +        //0~8000의 형태로 재배치하는 느낌..
맞는 접근이지만 그럼 -3<-2임에도 불구하고 벡터에서 -3이 -2보다 뒤에 위치하게 되겠네요?

2021-09-25 12:40 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2108.cpp
> +int main(){
p1
이 문제 안돌아가네요! 확인해주세요~

2021-09-25 12:40 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2503.cpp
> +    }
p2
오호 이건 조금 복잡하네요...! 이거보다 더 단순 무식하고 빠른 방법이 있어요!

2021-09-25 12:40 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2503.cpp
> +                // k는 1이 아닌 경우(**1, *1*) b++
👍

2021-09-25 12:40 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2503.cpp
> +        }
여기서 바로 return false를 해도 돼요!

2021-09-25 12:40 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2858.cpp
> +    }
p2
이건 조금 불필요한 연산이 많아보이네요! 우리는 전체의 타일 개수가 몇개인지 알고있어요!
그럼 가능한 가로길이와 세로길이의 후보는 어떻게 구하나요?

2021-09-26 07:39 UTC, rajoo1120 commented
고칠 수 있는 부분 다 고쳐봤습니다!! 리뷰부탁드립니다

2021-09-26 08:04 UTC, HyunJiLim0406 reviewed
p3
수고하셨습니다! 다 잘 수정하셨네요~
사소한 코멘트 하나만 그냥 읽어주시고 머지하셔도 좋습니다!

2021-09-26 08:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2108.cpp
> +            most = vec[tmp+4000]; //최빈값 갱신해주기
👍

2021-09-26 08:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2503.cpp
> +        }
좋아요! 근데 많은 조건이 한 문장에 들어가 있어서 조금 복잡하네요!
원래는 같은 일을 하는 연산은 합치는게 좋지만 이렇게 너무 길어지는 경우엔
'0이 존재하는지 체크하는 부분'과 '같은 숫자가 존재하는지 체크하는 부분'을 분리해도 좋아요

2021-09-26 08:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2858.cpp
> +    }
👍

2021-09-27 08:21 UTC, merged